### ISSUE TITLE
jQuery 2.1.4 multiple selectors not working

### ISSUE THREAD

**Issue by aicm** [hammerjs/jquery.hammer.js#44] opened 2015-11-23 02:10 UTC
Hello there,

It seems hammer cannot bind on a multiple selector, i.e. `$("#id1,#id2").hammer()...`

Here's the code: http://jsfiddle.net/1qacj0ct/2/
Here's the screen recording: https://www.dropbox.com/s/7q0185j4ikgcw9z/hammerjs-bug.mp4?dl=1

Thanks :+1:

**Comment by arschmitz** [comment] 2015-11-23 02:18
I believe this is is a problem with your code. You have a lot of unrelated code in your example a simple multiple selector example works just fine http://jsbin.com/ferinureje/edit?html,js,output

Im going to close this as cannot reproduce for now. If you still believe this is a bug in the library and can simplify your test case to demonstrate this i will be happy to re open this issue

**Comment by aicm** [comment] 2015-11-23 02:19
Load it up on a touch enabled device, preferably an iDevice.

**Closed as completed by arschmitz** 2015-11-23 02:18 UTC

**Comment by arschmitz** [comment] 2015-11-23 02:25
sorry copied bad save on that because i was not logged into jsbin and there was a reference error http://jsbin.com/batovu/edit?html,js,output and this is tested on multiple touch screen devices including iPhone iPad and several android devices

**Comment by aicm** [comment] 2015-11-23 02:36
It might have something to do with the fact that you have a different code, too.

Try http://jsbin.com/jilaroyiso/1/edit?html,js,output

Again, works on a desktop, doesn't on a touch enabled device. That's a bug. Otherwise it would fail on a desktop just the same, right?

Also, if .hammer() can't handle some simple if statements ...

**Comment by aicm** [comment] 2015-11-23 19:45
@arschmitz so? What do you think?

**Comment by arschmitz** [comment] 2015-11-23 19:47
@aicm the problem is being caused by setting the `touchAction` removing this ( which im guessing you dont really need ) should fix this. However this should not break things which im still trying to figure out

**Comment by aicm** [comment] 2015-11-23 19:49
Understood. No problem, I can live with separate code blocks per button. Thank you for looking into it and testing.
